apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-inference
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Emmanuel-Ashekun/edge-runtime-project
    targetRevision: HEAD
    path: helm-charts/edge-inference
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
